### ISSUE TITLE
basebot.BaseBot do not seem to respond to botrulez commands

### ISSUE THREAD

**Issue by EuphoricCatface** [CylonicRaider/basebot#7]
Please refer to my [nowbot](https://github.com/EuphoricCatface/NowBot/blob/master/nowbot.py). It responds to none of `!help`, `!help @NowBot`, `!ping`, `!uptime`.
Taking a look into `tumbleweed.py`, it seems that it has no reason to not respond to `!ping` and `!uptime` as well?

**Comment by EuphoricCatface** [comment]
O...kay, should have extended Bot instead of BaseBot. Still not works, figuring out what I've done wrong.

**Comment by EuphoricCatface** [comment]
Solved the problem by appending `basebot.Bot.handle_command` at the end of `handle_command`.

Man I've got so much to learn =D

**Comment by EuphoricCatface** [comment]
2/3 issues I opened today were fault of my ignorance .-.

**Comment by CylonicRaider** [comment]
Hmm... The manual already says that “In every case of overriding a method, the corresponding method of the parent class should be invoked, or undefined behavior occurs.”; the inline docs of `HeimEndpoint` do say something to that effect *enclosed in asterisks*.

The concrete issue aside, nitpicking, `now_handler` could be inlined into `handle_command`, or the whole code could be simplified by employing `MiniBot` instead of `Bot`.

**Comment by CylonicRaider** [comment]
> 2/3 issues I opened today were fault of my ignorance .-.

Regarding #6, make that “all three”.

**Comment by EuphoricCatface** [comment]
So that was what it meant. I did read that part but was just scanning by at the time. In my defense, the doc itself is fairly large and I lack some knowledge to understand them thoroughly :P 
`now_handler` is going to grow bigger :) although I'm expecting a few times of refactoring - maybe the filter for '!now' should go inline, and a function for each subcommend of !now

**Comment by CylonicRaider** [comment]
The manual is barely seven-eight pages long. I would suggest reading at least the “Object-oriented approach” section fully.
